'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Dye_Creator_BG3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ArrayOfArmorColor xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;ArmorColor&gt;
        '''    &lt;Nombre&gt;ARM_Camp_Rich_D_Blue&lt;/Nombre&gt;
        '''    &lt;Id&gt;0004915f-4399-4ae1-beab-85a62c11b674&lt;/Id&gt;
        '''    &lt;ParentId&gt;d0b540dd-c778-4573-b0cb-149a0309bfa2&lt;/ParentId&gt;
        '''    &lt;Source&gt;Replacement&lt;/Source&gt;
        '''    &lt;Components&gt;
        '''      &lt;Valores&gt;
        '''        &lt;string&gt;0.03921568 0.07066398 0.1254902&lt;/string&gt;
        '''        &lt;string&gt;0.2033388 0.2226916 0.2108136&lt;/strin [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Colores_Armaduras() As String
            Get
                Return ResourceManager.GetString("Colores_Armaduras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;save&gt;
        '''	&lt;version major=&quot;4&quot; minor=&quot;0&quot; revision=&quot;9&quot; build=&quot;0&quot; lslib_meta=&quot;v1,bswap_guids&quot; /&gt;
        '''	&lt;region id=&quot;MaterialPresetBank&quot;&gt;
        '''		&lt;node id=&quot;MaterialPresetBank&quot;&gt;
        '''			&lt;children&gt;
        '''				&lt;node id=&quot;Resource&quot;&gt;
        '''					&lt;attribute id=&quot;ID&quot; type=&quot;FixedString&quot; value=&quot;05eb6574-d2d8-078c-659a-9a4f44039866&quot; /&gt;
        '''					&lt;attribute id=&quot;Name&quot; type=&quot;LSString&quot; value=&quot;DYE_ARM_WhiteBlue_01&quot; /&gt;
        '''					&lt;attribute id=&quot;_OriginalFileVersion_&quot; type=&quot;int64&quot; value=&quot;144115207403209023&quot; /&gt;
        '''					&lt;children&gt; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property DyesOriginales() As String
            Get
                Return ResourceManager.GetString("DyesOriginales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Azure_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Azure_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlackBlue_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlackBlue_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlackGreen_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlackGreen_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlackPink_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlackPink_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlackRed_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlackRed_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlackTeal_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlackTeal_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Blue_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Blue_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlueGreen_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlueGreen_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BluePurple_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BluePurple_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlueYellow_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlueYellow_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_BlueYellow_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_BlueYellow_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Golden_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Golden_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Green_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Green_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Green_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Green_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_GreenPink_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_GreenPink_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_GreenSage_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_GreenSage_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_GreenSwamp_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_GreenSwamp_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_IceCream_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_IceCream_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_IceCream_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_IceCream_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_IceCream_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_IceCream_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_IceCream_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_IceCream_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Maroon_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Maroon_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Ocean_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Ocean_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Orange_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Orange_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_OrangeBlue_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_OrangeBlue_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Pink_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Pink_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Purple_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Purple_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Purple_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Purple_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Purple_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Purple_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Purple_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Purple_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_PurpleRed_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_PurpleRed_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_RedBrown_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_RedBrown_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_RedWhite_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_RedWhite_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Remover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Remover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_RichRed_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_RichRed_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_RoyalBlue_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_RoyalBlue_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_Teal_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_Teal_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_WhiteBlack_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_WhiteBlack_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_WhiteBrown_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_WhiteBrown_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Dye_WhiteRed_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Dye_WhiteRed_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LOOT_Laboratory_Flask_Glass_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LOOT_Laboratory_Flask_Glass_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
