' This file is used by Code Analysis to maintain SuppressMessage
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button10_Click_1(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button2_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button3_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button4_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button5_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button6_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Button7_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Cargar(System.String)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.CheckBox2_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.ComboBox1_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.ComboBox2_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.ComboBox3_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.copiar_base(System.String)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Darker(System.Windows.Forms.Button,System.Boolean)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.DePicture_a_Texto(System.Windows.Forms.PictureBox@,System.Windows.Forms.TextBox@)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.DeTexto_aPicture(System.Windows.Forms.TextBox@,System.Windows.Forms.PictureBox@)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.filtra_arbol")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.findallchildren(System.Windows.Forms.TreeNode,System.String)~System.Boolean")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Form1_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.llen_armaduras")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.lock(System.Boolean)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Repinta")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.selecciona_Icono")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Selectpar(System.Windows.Forms.Button)~System.Windows.Forms.TextBox")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Selectpar(System.Windows.Forms.PictureBox)~System.Windows.Forms.TextBox")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Selectpar(System.Windows.Forms.TextBox)~System.Windows.Forms.PictureBox")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.SRGB0_1(System.Byte,System.Byte,System.Byte)~System.String")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.SRGB0_1(System.String)~System.Drawing.Color")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.TextBoxDescrip_TextChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.TreeView1_AfterSelect(System.Object,System.Windows.Forms.TreeViewEventArgs)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validar la compatibilidad de la plataforma", Justification:="<pendiente>", Scope:="type", Target:="~T:Dye_Creator_BG3.Form1")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Llen_armaduras")>
<Assembly: SuppressMessage("Performance", "CA1829:Usar la propiedad Length/Count en lugar de Count() cuando esté disponible", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.SRGB0_1(System.String)~System.Drawing.Color")>
<Assembly: SuppressMessage("Performance", "CA1862:Use las sobrecargas del método ""StringComparison"" para realizar comparaciones de cadenas sin distinción de mayúsculas y minúsculas", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Filtra_arbol")>
<Assembly: SuppressMessage("Performance", "CA1829:Usar la propiedad Length/Count en lugar de Count() cuando esté disponible", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Copiar_base(System.String)")>
<Assembly: SuppressMessage("Performance", "CA1862:Use las sobrecargas del método ""StringComparison"" para realizar comparaciones de cadenas sin distinción de mayúsculas y minúsculas", Justification:="<pendiente>", Scope:="member", Target:="~M:Dye_Creator_BG3.Form1.Findallchildren(System.Windows.Forms.TreeNode,System.String)~System.Boolean")>
